# We use our own Perl setup (language "generic" uses a stripped-down TravisCI image)
language: generic
virt: lxd
# TravisCI does not support lxd (containers) with amd64
arch: arm64
os: linux
# Ubuntu 18.04 "Bionic" (Debian Buster equivalent)
dist: bionic

env:
    global:
        # assume the Git submodule is cloned into config/ according to .gitmodules
        - OXI_TEST_SAMPLECONFIG_DIR=$TRAVIS_BUILD_DIR/config
        - OXI_TEST_DB_MYSQL_NAME=openxpki
        - OXI_TEST_DB_MYSQL_USER=openxpki
        - OXI_TEST_DB_MYSQL_PASSWORD=openxpki
        - OXI_TEST_DB_MYSQL_DBUSER=root
        - OXI_TEST_DB_MYSQL_DBPASSWORD=
    jobs:
        - OXI_TEST_RUN=unit_coverage
        - OXI_TEST_RUN=api2
        - OXI_TEST_RUN=webui
        - OXI_TEST_RUN=client

cache:
    directories:
        - $HOME/perl5/lib/perl5

before_cache:
    - |
      while read -d : path; do
        test $path == "." && continue;
        echo "Purging $path/OpenXPKI*";
        rm -rf $path/OpenXPKI*;
        rm -rf $path/auto/OpenXPKI*;
      done <<< $(perl -e 'print "$_:" for @INC')

#  - rm -Rf $HOME/perl5/lib/perl5/x86_64-linux-gnu-thread-multi/OpenXPKI

#
# OS packages
#
addons:
  apt:
    packages:
    - openssl
    - libssl-dev
    - pkg-config
    - cpanminus
    - figlet
#  mariadb: '10.1'
#  ... doesn't work, throws apt error messages because it conflicts with MySQL

#
# Service setup
#
before_install:
    - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 0xf1656f24c74cd1d8
    - sudo apt-get -q update
    - sudo apt-get -y purge mysql-client-5.7 mysql-client-core-5.7 mysql-common mysql-server-5.7 mysql-server-core-5.7
    # we need to prevent invoke-rc.d from starting MariaDB as this would make
    # the TravisCI LXD container hang forever. So we pretend it's runlevel 1
    # where most services aren't started: (https://askubuntu.com/a/221938)
    - sudo echo -e '#!/bin/sh\nexit 101' | sudo install -m 755 /dev/stdin /usr/sbin/policy-rc.d && sudo apt-get -y install mariadb-server-10.1 libmariadbclient-dev && sudo rm -f /usr/sbin/policy-rc.d
    # now start MariaDB in background
    - sudo /usr/bin/mysqld_safe 2>&1 >/dev/null &
    # create database
    - sudo ./tools/testenv/mysql-wait-for-db.sh
    - sudo ./tools/testenv/mysql-create-db.sh
    - sudo ./tools/testenv/mysql-create-user.sh
    - sudo ./tools/testenv/mysql-create-schema.sh
    # setup cpanm
    - cpanm --local-lib=~/perl5 local::lib && eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)

#
# Dependencies / modules
#
install:
    - cpanm --quiet --notest PPI
    - ./tools/scripts/makefile2cpanfile.pl > ./cpanfile
    - cpanm --quiet --notest --installdeps ./
    # We need to reinstall Devel::Cover because we told TravisCI to cache
    # ~/perl5/lib/perl5 but not ~/perl5/bin - so on next run the "cover"
    # script will be gone
    - cpanm --quiet --notest --reinstall Devel::Cover
    - cpanm --quiet --notest Devel::Cover::Report::Coveralls

#
# Build
#
# (must be specified if "language" is "generic")
script:
    - which perl
    - perl -v
    - ./tools/scripts/travis-install-and-test.sh
